version: '3.5'

services:
  server:
    command: /start.sh
    ports:
      - ${APP_PORT_PROD}:80

  db:
    image: postgres:9.4
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  dbdata:
